# high-priority.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority # Used in Pods
value: 1000000 # Higher than the system default (1000000000 is reserved)
globalDefault: false
description: "Top priority for CIP"
