all:
  children:
    app:
      hosts:
        arc.hopto.org:
          ansible_user: root
          # add more hosts under app: as needed

    controller:
      hosts:
        localhost:
          ansible_connection: local
